[project]
name = "sql-connection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=0.4.1",
    "mysql-connector-python>=9.2.0",
    "python-dotenv>=1.0.1",
]
